return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {
        "c",
        "cpp",
        "python",
        "javascript",
        "typescript",
        "tsx",
        "html",
        "css",
        "rust",
        "go",
        "lua",
        "luap",
        "luadoc",
        "json",
        "jsonc",
        "yaml",
        "toml",
        "markdown",
        "markdown_inline",
        "help",
        "regex",
      },
    },
  },
}
